---
sudo: required
dist: bionic

notifications:
  slack:
    on_failure: always

matrix:
  fast_finish: true
  include:

    - name: "Python 3.7 on bionic arm64" # package architecture (amd64) does not match system (arm64)
      os: linux
      arch: arm64
      dist: bionic
      language: python
      python: 3.7
      # env:
      #   - LIB_PATH="/usr/bin/shared/x86_64/v1"
      # compiler:
      #  - gcc
      #  - clang
      before_install:
        - pip3 install virtualenv
        - virtualenv -p $(which python3) ~venvpy3
        - source ~venvpy3/bin/activate
      after_success:
        - deactivate

    - name: "Python 3.7 on xenial arm64"
      os: linux
      arch: arm64
      dist: xenial
      language: python
      python: 3.7
      # env:
      #   - LIB_PATH="/usr/bin/shared/x86_64/v1"
      # compiler:
      #  - gcc
      #  - clang
      before_install:
        - pip3 install virtualenv
        - virtualenv -p $(which python3) ~venvpy3
        - source ~venvpy3/bin/activate
      after_success:
        - deactivate
    



